import { AdProps } from "./AdBase";

export const angles: AdProps[] = [
  {
    tag: "Free Consultation",
    headline1: "Your competitors",
    headline2: "are online.",
    headlineAccent: "Are you?",
    body: "If customers can't find you, they're finding someone else.\nGet a professional website built in 7 days.",
    cta: "Get Your Free Consultation",
    voiceover: "vo-angle1.mp3",
  },
  {
    tag: "Website Redesign",
    headline1: "Your website is",
    headline2: "costing you",
    headlineAccent: "clients.",
    body: "First impressions happen online. An outdated site loses leads\nbefore they ever contact you.",
    cta: "Upgrade Your Website Today",
    voiceover: "vo-angle2.mp3",
  },
  {
    tag: "Real Results",
    headline1: "Built for clients",
    headline2: "in Canada and",
    headlineAccent: "Indonesia.",
    body: "Clean design. Fast delivery. Affordable price.\nYour business deserves a website that works.",
    cta: "See Our Work",
    voiceover: "vo-angle3.mp3",
  },
  {
    tag: "Affordable",
    headline1: "Professional sites",
    headline2: "don't have to be",
    headlineAccent: "expensive.",
    body: "Mobile-ready, fast, and clean — built for small businesses\nat prices that actually make sense. No hidden fees.",
    cta: "Get a Free Quote",
    voiceover: "vo-angle4.mp3",
  },
  {
    tag: "Trusted Portfolio",
    headline1: "We built",
    headline2: "international",
    headlineAccent: "platforms.",
    body: "parallaxnet.ca and parallaxnet.id — now bringing the same\nquality to small businesses like yours.",
    cta: "Get Your Free Consultation",
    voiceover: "vo-angle5.mp3",
  },
  {
    tag: "Free Demo",
    headline1: "See your business",
    headline2: "as a",
    headlineAccent: "website.",
    body: "We build you a free working demo first.\nYou only pay if you love it. No deposit.",
    cta: "Chat us, get your free demo",
    voiceover: "vo-angle6.mp3",
  },
  {
    tag: "Free Demo - Risk Free",
    headline1: "Pay nothing",
    headline2: "until you",
    headlineAccent: "see it.",
    body: "Send your business name. Get a real demo page built for you.\nZero upfront, zero risk.",
    cta: "Get my free demo",
    voiceover: "vo-angle7.mp3",
  },
  {
    tag: "Free Demo - Fast",
    headline1: "Your demo site,",
    headline2: "ready in",
    headlineAccent: "3 days.",
    body: "No deposit. We design it, you decide.\nSimple, fast, yours to keep if you love it.",
    cta: "Start free, chat now",
    voiceover: "vo-angle8.mp3",
  },
];
